### PR TITLE
Add instructions for deploying to Cloud Run

### PR DESCRIPTION
**Pull request by averikitsch**

### CODE REVIEW

**Comment by jnolis** [comment]
Thanks for sending these over! I want to make sure that the master branch is as straightforward to use as possible, so could we make this a new gcp branch? Thanks!

**Comment by averikitsch** [comment]
Since I don't have write permission to this repo - If you push a new branch I can direct this PR towards that or if you update the write permissions I can push the branch directly. Thanks!

**Comment by jnolis** [comment]
I just made a new branch for this and added you as a collaborator, so you should be good to go!

**Comment by averikitsch** [comment]
Thanks for adding me! You can now find this code on branch `google-cloud-run`. Let me know if you have any questions.

**Pull request closed without merging**
